# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1351]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [1352]:
A = np.arange(1, 16).reshape(3,5)
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [1353]:
print("Dimension of matrix A (number of axes) is :", A.ndim)
print("Shape:", A.shape)
print("Size (number of elements):", A.size)
print("Data type:", A.dtype)

Dimension of matrix A (number of axes) is : 2
Shape: (3, 5)
Size (number of elements): 15
Data type: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [1354]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [1355]:
#Element wise subtraction
subtraction = B - C
print("Elementwise Subtraction (B - C):")
print(subtraction.astype(int))
print()

Elementwise Subtraction (B - C):
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]



In [1356]:
#Element wise multiplication
multiplication = B * C
print("Elementwise multiplication (B * C):")
print(multiplication.astype(int))
print()

Elementwise multiplication (B * C):
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]



In [1357]:
# Matrix wise multiplication
matrix_multiplication = B @ C
print("matrix_multiplication (B @ C):")
print(matrix_multiplication.astype(int))
print()

matrix_multiplication (B @ C):
[[12 12 12]
 [30 30 30]
 [48 48 48]]



### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [1358]:
# Below are the given data for the questions set
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [1359]:
# Exponentiate each number elementwise
exp_B = np.exp(B)
print("Exponentiated Matrix (elementwise):")
print(exp_B.astype(int))
print()

Exponentiated Matrix (elementwise):
[[   2    7   20]
 [  54  148  403]
 [1096 2980 8103]]



In [1360]:
# Calculate the minimum value in the whole matrix
min_value = np.min(B)
print("Minimum value in the whole matrix:")
print(min_value)

Minimum value in the whole matrix:
1


In [1361]:
# Calculate the minimum value in each row
min_value_rows = np.min(B, axis=1)
print("Minimum value in each row:")
print(min_value_rows)


Minimum value in each row:
[1 4 7]


In [1362]:
#Calculate the minimum value in each column
min_value_columns = np.min(B, axis=0)
print("Minimum value in each column:")
print(min_value_columns)

Minimum value in each column:
[1 2 3]


In [1363]:
#Find the index value for the minimum value in the whole matrix
min_index = np.argmin(B)
print("Index of the minimum value in the whole matrix:")
print(min_index)

Index of the minimum value in the whole matrix:
0


In [1364]:
#Find the index value for the minimum value in each row
min_indices_rows = np.argmin(B, axis=1)
print("Indices of the minimum value in each row:")
print(min_indices_rows)

Indices of the minimum value in each row:
[0 0 0]


In [1365]:
#Calculate the sum for all elements
sum_all = np.sum(B)
print("Sum of all elements:")
print(sum_all)

Sum of all elements:
45


In [1366]:
#Calculate the mean for each column
mean_columns = np.mean(B, axis=0)
print("Mean of each column:")
print(mean_columns.astype(int))

Mean of each column:
[4 5 6]


In [1367]:
#Calculate the median for each column
median_columns = np.median(B, axis=0)
print("Median of each column:")
print(median_columns.astype(int))

Median of each column:
[4 5 6]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [1368]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [1369]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

When we slice a multi-dimensional array and provide fewer indices than axes, NumPy assumes the missing indices are referring to the entire range of that axis. In this example A[1] has been sliced from the main matrix A.So Numpy assumes we're selecting all elements along the remaining axes of 1. Hence it is printing array([ 6,  7,  8,  9, 10]).

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate through the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [1370]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [1371]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [1372]:
# Default iteration (row-wise)
print("Row-wise iteration:")
for row in A:
    print(row)

Row-wise iteration:
[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [1373]:
# Elementwise iteration we can do by using numpy.nditer
print("Elementwise iteration (using nditer):")
for elem in np.nditer(A):
    print(elem)

Elementwise iteration (using nditer):
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [1374]:
# Elementwise iteration using ravel()
print("Elementwise iteration (using ravel()):")
for elem in A.ravel():
    print(elem)

Elementwise iteration (using ravel()):
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [1375]:
# Elementwise iteration using flatten()
print("Elementwise iteration (using flatten()):")
for elem in A.flatten():
    print(elem)

Elementwise iteration (using flatten()):
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [1376]:
#Another way of printing element wise using a for loop
for i in range(A.shape[0]):  # Loop over rows
    for j in range(A.shape[1]):  # Loop over columns
        print(A[i, j])

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [1377]:
#Another way of printing element wise using reshape()
for x in A.reshape(-1):  # -1 tells numpy to flatten the array
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [1378]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(" a = ")
print(a)
print()
print(" b = ")
print(b)

 a = 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

 b = 
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


a = np.arange(30):

This line creates a 1D array called a with numbers starting from 0 up to 29.

b = a.reshape((2, 3, -1)):

This reshapes the 1D array a into a 3D array b. The shape is (2, 3, ?).
The first dimension, 2, means there are 2 blocks in the array.
The second dimension, 3, means each block will have 3 rows.
The third dimension, -1, is calculated automatically by NumPy based on the total number of elements in a. 
Since the total number of elements is 30, and we already set the first two dimensions (2 and 3), 
Total elements in a: 30.
Dividing 30 by 2×3: 30/6=5
, so the third dimension becomes 5.
The final shape of b: (2, 3, 5).

First, the original 1D array a is printed.
Then, the reshaped 3D array b is printed.print
The 3D array b has three dimensions, which are called axes:

Axis 0 (Blocks):

This is the first dimension. It represents the outermost structure of the array.
b has 2 blocks.
Axis 1 (Rows):

This is the second dimension. It represents the rows inside each block.
b has 3 rows in each block.
Axis 2 (Columns):

This is the third dimension. It represents the elements (columns) inside each row.
b has 5 columns in each row.

To access a specific element in b, we need three indices: [block, row, column].



The code reshapes a 1D array into a 3D array. The new array b has a shape (2, 3, 5), meaning:

It has 2 blocks.
Each block has 3 rows.
Each row has 5 columns.
By using three indices, we can access any element in the 3D array.

### For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
### Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

### If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

### Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [1379]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [1380]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [1381]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [1382]:
import numpy as np

def add_mult_matrices(A, B, operation):
    # Validate that the inputs are numpy arrays
    if not isinstance(A, np.ndarray) or not isinstance(B, np.ndarray):
        raise ValueError("Both inputs must be of type numpy.ndarray")
    
    # Validate that the operation is either 'add' or 'multiply'
    if operation not in ['add', 'multiply']:
        raise ValueError("The operation must be either 'add' or 'multiply'")
    
    # Matrix Addition
    if operation == 'add':
        # Validate that the matrices have the same shape for addition
        if A.shape != B.shape:
            raise ValueError("Matrices must have the same shape for addition")
        return A + B
    
    # Matrix Multiplication
    elif operation == 'multiply':
        # Validate that the number of columns of A is equal to the number of rows of B
        if A.shape[1] != B.shape[0]:
            raise ValueError("Number of columns of A must equal the number of rows of B for multiplication")
        return np.dot(A, B)

# Example usage:
A = np.array([[5, 3], [7, 9]])
B = np.array([[2, 8], [6, 3]])

# Addition example
result_add = add_mult_matrices(A, B, 'add')
print("Matrix Addition Result:\n", result_add)

# Multiplication example
result_multiply = add_mult_matrices(A, B, 'multiply')
print("Matrix Multiplication Result:\n", result_multiply)


Matrix Addition Result:
 [[ 7 11]
 [13 12]]
Matrix Multiplication Result:
 [[28 49]
 [68 83]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. 

### Define the Vector(In Python, numpy is use  for working with vectors and matrices. 

In [1383]:
# import numpy and define the vector 𝑥.)
import numpy as np
x = np.array([4, 3])  ## x is represented as a NumPy array:x = [4,3]

In [1384]:
#10.1.1 (a) What dimension does the vector x have? Vilken dimension har vektorn x ?
dimension = x.ndim
print(f"(a) Dimension of x: {dimension}")

(a) Dimension of x: 1


In [1385]:
# 10.1.1 (b) Calculate 5x . Beräkna 5x.
five_x = 5 * x # scalar multiplication (5 * [4, 3])
print(f"  First element: 5 * {x[0]} = {5 * x[0]}")
print(f"  Second element: 5 * {x[1]} = {5 * x[1]}")
#Print the final result
print(f"5x: {five_x}")

  First element: 5 * 4 = 20
  Second element: 5 * 3 = 15
5x: [20 15]


In [1386]:
#10.1.1 (c) Calculate 3𝑥. Beräkna 3x.
x = np.array([4, 3])  # x = [4, 3]
three_x = 3 * x # scalar multiplication (3 * [4, 3])
print(f"  First element: 3 * {x[0]} = {3 * x[0]}")
print(f"  Second element: 3 * {x[1]} = {3 * x[1]}")
#Print the final result
print(f"(c) 3x: {three_x}")

  First element: 3 * 4 = 12
  Second element: 3 * 3 = 9
(c) 3x: [12  9]


In [1387]:
#10.1.1 (d) Calculate 5𝑥 + 3𝑥. Beräkna 5x + 3x.
x = np.array([4, 3])  # x = [4, 3]
print("Vector x :\n",x)
#  Calculate 5x
five_x = 5 * x  # Scalar multiplication
print(f" 5x = {five_x}")
#  Calculate 3x
three_x = 3 * x  # Scalar multiplication
print(f" 3x = {three_x}")
#  Perform element-wise addition
sum_five_and_three_x = five_x + three_x  # Add corresponding elements
print(f"5x = {five_x}, 3x = {three_x}")  # Show individual vectors
print(f" Add 5x and 3x element-wise:")
print(f"  First element: {five_x[0]} + {three_x[0]} = {sum_five_and_three_x[0]}")
print(f"  Second element: {five_x[1]} + {three_x[1]} = {sum_five_and_three_x[1]}")
print(f"Result: 5x + 3x = {sum_five_and_three_x}")


Vector x :
 [4 3]
 5x = [20 15]
 3x = [12  9]
5x = [20 15], 3x = [12  9]
 Add 5x and 3x element-wise:
  First element: 20 + 12 = 32
  Second element: 15 + 9 = 24
Result: 5x + 3x = [32 24]


In [1388]:
#10.1.1 (e) Calculate 8𝑥. Beräkna 8x.
x = np.array([4, 3])  # x = [4, 3]
eight_x = 8 * x #  scalar multiplication (8 * [4, 3])
print(f"  First element: 8 * {x[0]} = {8 * x[0]}")
print(f"  Second element: 8 * {x[1]} = {8 * x[1]}")
#Print the final result
print(f"(e) 8x: {eight_x}")


  First element: 8 * 4 = 32
  Second element: 8 * 3 = 24
(e) 8x: [32 24]


In [1389]:
#10.1.1 (f) Calculate 4𝑥 − 𝑥. Beräkna 4x − x.
x = np.array([4, 3])  # x = [4, 3]
# Calculate 4x
four_x = 4 * x  # Scalar multiplication
print(f" 4x = {four_x}")
# Subtract x from 4x
four_x_minus_x = four_x - x  # Element-wise subtraction
print(f" Subtract x from 4x:")
print(f"  First element: {four_x[0]} - {x[0]} = {four_x_minus_x[0]}")
print(f"  Second element: {four_x[1]} - {x[1]} = {four_x_minus_x[1]}")

# Print the final result
print(f"(f) 4x - x: {four_x_minus_x}")


 4x = [16 12]
 Subtract x from 4x:
  First element: 16 - 4 = 12
  Second element: 12 - 3 = 9
(f) 4x - x: [12  9]


In [1390]:
#10.1.1 (g) Transpose of 𝑥. Ber¨akna x⊤, vilken blir den nya dimensionen efter att transponeringen utf¨orts?
x = np.array([4, 3])  # x = [4, 3]
x_transpose = x.reshape(-1, 1)  # Reshape to a column vector
# Print intermediate results
print(f"Original vector x: {x} (Shape: {x.shape})")
print(f"Reshaping x to a column vector:")
print(f"Transpose of x:\n{x_transpose}")
print(f"(g) Dimension after transpose: {x_transpose.shape}")


Original vector x: [4 3] (Shape: (2,))
Reshaping x to a column vector:
Transpose of x:
[[4]
 [3]]
(g) Dimension after transpose: (2, 1)


In [1391]:
#10.1.1 (h) Is 𝑥 + 𝑥⊤ defined? Är x + x ⊤ definierat?
x_transpose = x.reshape(-1, 1)  # Transpose of x

# Check if addition is defined
is_defined = x.shape == x_transpose.shape  # Check if shapes are equal

#  Print the results
print(f"Original vector x: {x} (Shape: {x.shape})")
print(f"Transpose of x:\n{x_transpose} (Shape: {x_transpose.shape})")
print(f"(h) Is x + xᵀ defined? {is_defined}")
print("Since the sizes are different hence false indicates this addition is not possible")


Original vector x: [4 3] (Shape: (2,))
Transpose of x:
[[4]
 [3]] (Shape: (2, 1))
(h) Is x + xᵀ defined? False
Since the sizes are different hence false indicates this addition is not possible


In [1392]:
#10.1.1 (i) Calculate ∥x∥. Ber¨akna ∥x∥.
x = np.array([4, 3])

# Compute the squares of each element
squares = x ** 2  # Element-wise squaring
print(f"Squares of each element in x: {squares}")

# Sum the squared elements
sum_of_squares = np.sum(squares)  # Sum of the squared elements
print(f" Sum of squares: {sum_of_squares}")

# Take the square root of the sum
norm_x = np.sqrt(sum_of_squares)  # Square root of the sum of squares
print(f" Square root of the sum of squares (norm): {norm_x}")

#  Alternatively, use np.linalg.norm for simplicity
norm_x_direct = np.linalg.norm(x)
print(f"(i) ||x|| calculated using np.linalg.norm: {norm_x_direct}")


Squares of each element in x: [16  9]
 Sum of squares: 25
 Square root of the sum of squares (norm): 5.0
(i) ||x|| calculated using np.linalg.norm: 5.0


In [1393]:
# Uppgift 10.1.2
import numpy as np
v = np.array([[3], [7], [0], [11]])  # Define the vector
print(f"Vector v:\n {v}")



Vector v:
 [[ 3]
 [ 7]
 [ 0]
 [11]]


In [1394]:
#10.1.2 (a) Find the dimension of 𝑣. Vilken dimension har vektorn v?
dimension_v = v.reshape(1, 4)  # Count the elements in v
print("Dimension of the vector:", dimension_v.shape)


Dimension of the vector: (1, 4)


In [1395]:
#10.1.2 (b) Calculate 2𝑣. Beräkna 2v.
v = np.array([[3], [7], [0], [11]])

# Calculate 2v by multiplying each element of v by 2
two_v = 2 * v  # This is element-wise multiplication

# Print the result
print(f"(b) 2v:\n {two_v}")


(b) 2v:
 [[ 6]
 [14]
 [ 0]
 [22]]


In [1396]:
#10.1.2 (c) Calculate 5𝑣 + 2𝑣. Beräkna 5v + 2v.
v = np.array([[3], [7], [0], [11]]) # Define the vector

# Calculate 5v by multiplying each element of v by 5
five_v = 5 * v  
# Calculate 2v by multiplying each element of v by 2
two_v = 2 * v  

#  Add 5v and 2v element-wise
print("Element-wise addition of 5v and 2v:")
for i in range(len(v)):  # Loop over each element
    result = five_v[i] + two_v[i]
    print(f"5v[{i}] + 2v[{i}] = {five_v[i]} + {two_v[i]} = {result}")

# print the final result of 5v + 2v
sum_five_and_two_v = five_v + two_v
print(f"\nThe resulting vector (5v + 2v):\n {sum_five_and_two_v}")


Element-wise addition of 5v and 2v:
5v[0] + 2v[0] = [15] + [6] = [21]
5v[1] + 2v[1] = [35] + [14] = [49]
5v[2] + 2v[2] = [0] + [0] = [0]
5v[3] + 2v[3] = [55] + [22] = [77]

The resulting vector (5v + 2v):
 [[21]
 [49]
 [ 0]
 [77]]


In [1397]:
#10.1.2 (d) Calculate 4𝑣 − 2𝑣. Beräkna 4v − 2v.
v = np.array([[3], [7], [0], [11]]) # Define the vector

# Calculate 4v by multiplying each element of v by 4
four_v = 4 * v  
# Calculate 2v by multiplying each element of v by 2
two_v = 2 * v  
#  Subtract  5v and 2v element-wise
print("Element-wise subtraction of 4v and 2v:")
for i in range(len(v)):  # Loop over each element
    result = four_v[i] - two_v[i]
    print(f"4v[{i}] - 2v[{i}] = {four_v[i]} - {two_v[i]} = {result}")

#  print the final result of 4v - 2v
four_v_minus_two_v = four_v - two_v
print(f"\nThe resulting vector (4v - 2v):\n {four_v_minus_two_v}")



Element-wise subtraction of 4v and 2v:
4v[0] - 2v[0] = [12] - [6] = [6]
4v[1] - 2v[1] = [28] - [14] = [14]
4v[2] - 2v[2] = [0] - [0] = [0]
4v[3] - 2v[3] = [44] - [22] = [22]

The resulting vector (4v - 2v):
 [[ 6]
 [14]
 [ 0]
 [22]]


In [1398]:
#10.1.2 (e) Calculate v⊤, what will be the new dimension after the transposition is performed?
#Beräkna v⊤, vilken blir den nya dimensionen efter atttransponeringen utförts?
v = np.array([[3], [7], [0], [11]]) # Define the vector
v_transpose = v.reshape(1, -1)  # Reshape to a row vector
# Print intermediate results
print(f"Original vector v:\n {v} (Shape: {v.shape})")
print(f"Reshaping x to a column vector:")
print(f"Transpose of v:\n{v_transpose}")
print(f"(e) Dimension after transpose: {v_transpose.shape}")

Original vector v:
 [[ 3]
 [ 7]
 [ 0]
 [11]] (Shape: (4, 1))
Reshaping x to a column vector:
Transpose of v:
[[ 3  7  0 11]]
(e) Dimension after transpose: (1, 4)


In [1399]:
#10.1.2 (f) Calculate ∥v∥.Beräkna ∥v∥.
v = np.array([[3], [7], [0], [11]]) # Define the vector
squares = v ** 2  # Element-wise squaring
print(f"Squares of each element in v:\n {squares}")

#  Sum the squared elements
sum_of_squares = np.sum(squares)  # Sum of the squared elements
print(f"Sum of squares: {sum_of_squares}")

norm_v = np.sqrt(sum_of_squares)  # Square root of the sum of squares
print(f"Square root of the sum of squares (norm): {norm_v}")

#  use np.linalg.norm for simplicity
norm_v_direct = np.linalg.norm(v)  # Use NumPy's built-in norm function
print(f"(f) ||v|| calculated using np.linalg.norm: {norm_v_direct}")

Squares of each element in v:
 [[  9]
 [ 49]
 [  0]
 [121]]
Sum of squares: 179
Square root of the sum of squares (norm): 13.379088160259652
(f) ||v|| calculated using np.linalg.norm: 13.379088160259652


In [1400]:
# Uppgift 10.1.3 Define the vectors v1 = (4, 3, 1, 5) and v2 = (2, 3, 1, 1).
#10.1.3 (a) Calculate ∥v1∥.Beräkna ∥v1∥.
v1 = np.array([4, 3, 1, 5]) # Define the vector v1

squares = v1 ** 2  # Element-wise squaring of v1
print(f"Squares of each element in v1: {squares}")

sum_of_squares = np.sum(squares)  # Sum of the squared elements
print(f"Sum of squares: {sum_of_squares}")

norm_v1 = np.sqrt(sum_of_squares)  # Square root of the sum of squares
print(f"Square root of the sum of squares (norm): {norm_v1}")

norm_v1_direct = np.linalg.norm(v1)  #  NumPy's built-in norm function
print(f"(a) ||v1|| calculated using np.linalg.norm: {norm_v1_direct}")

Squares of each element in v1: [16  9  1 25]
Sum of squares: 51
Square root of the sum of squares (norm): 7.14142842854285
(a) ||v1|| calculated using np.linalg.norm: 7.14142842854285


In [1401]:
#10.1.3 (b) Calculate ∥v1 − v2∥.Beräkna ∥v1 − v2∥.

v1 = np.array([4, 3, 1, 5]) # Define the vector v1
v2 = np.array([2, 3, 1, 1]) # Define the vector v2

#  Subtract v2 from v1 (element-wise subtraction)
v1_minus_v2 = v1 - v2
for i in range(len(v1)):  # Loop over each element
    result = v1[i] - v2[i]
    print(f"v1[{i}] - v2[{i}] = {v1[i]} - {v2[i]} = {result}")

#  Calculate the norm of the resulting vector
v1_minus_v2 = v1 - v2
norm_v1_minus_v2 = np.linalg.norm(v1_minus_v2)
print(f"\nThe resulting vector (v1 - v2): {v1_minus_v2}")

squares = v1_minus_v2 ** 2  # Element-wise squaring of v1
print(f"Squares of each element in v1: {squares}")

#  Sum the squared elements
sum_of_squares = np.sum(squares)  # Sum of the squared elements
print(f"Sum of squares: {sum_of_squares}")

#  Take the square root of the sum (Euclidean norm)
norm_v1 = np.sqrt(sum_of_squares)  # Square root of the sum of squares
print(f"Square root of the sum of squares (norm): {norm_v1}")

print(f"(b) ||v1 - v2||: {norm_v1_minus_v2}")

v1[0] - v2[0] = 4 - 2 = 2
v1[1] - v2[1] = 3 - 3 = 0
v1[2] - v2[2] = 1 - 1 = 0
v1[3] - v2[3] = 5 - 1 = 4

The resulting vector (v1 - v2): [2 0 0 4]
Squares of each element in v1: [ 4  0  0 16]
Sum of squares: 20
Square root of the sum of squares (norm): 4.47213595499958
(b) ||v1 - v2||: 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [1402]:
#Uppgift 10.2.1. Define the matrices:
import numpy as np

# Define matrices
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.eye(2)  # Identity matrix

In [1403]:
#If it is defined, perform the following calculations:
#10.2.1 (a) 2A
A = np.array([[2, 1, -1], [1, -1, 1]])
print( "Matrix A :\n", A)
#  multiplication by 2 (2A)
two_A = 2 * A


#  Print the final result (2A)
print(f"\nResult of 2A: \n{two_A}")

Matrix A :
 [[ 2  1 -1]
 [ 1 -1  1]]

Result of 2A: 
[[ 4  2 -2]
 [ 2 -2  2]]


In [1404]:
#10.2.1 (b) B − 2A
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])#  scalar multiplication 2A
two_A = 2 * A

#  Print every  steps for 2A
print(f"First row of A: {A[0]}")
print(f"  First element: 2 * {A[0][0]} = {2 * A[0][0]}")
print(f"  Second element: 2 * {A[0][1]} = {2 * A[0][1]}")
print(f"  Third element: 2 * {A[0][2]} = {2 * A[0][2]}")

print(f"Second row of A: {A[1]}")
print(f"  First element: 2 * {A[1][0]} = {2 * A[1][0]}")
print(f"  Second element: 2 * {A[1][1]} = {2 * A[1][1]}")
print(f"  Third element: 2 * {A[1][2]} = {2 * A[1][2]}")

#  matrix subtraction B - 2A
result_B_minus_2A = B - two_A

#  Print every steps for B - 2A (element-wise subtraction)
print("\nPerforming subtraction: B - 2A")

# First row subtraction
print(f"First row of B: {B[0]}")
print(f"  First element: {B[0][0]} - {two_A[0][0]} = {B[0][0] - two_A[0][0]}")
print(f"  Second element: {B[0][1]} - {two_A[0][1]} = {B[0][1] - two_A[0][1]}")
print(f"  Third element: {B[0][2]} - {two_A[0][2]} = {B[0][2] - two_A[0][2]}")

# Second row subtraction
print(f"Second row of B: {B[1]}")
print(f"  First element: {B[1][0]} - {two_A[1][0]} = {B[1][0] - two_A[1][0]}")
print(f"  Second element: {B[1][1]} - {two_A[1][1]} = {B[1][1] - two_A[1][1]}")
print(f"  Third element: {B[1][2]} - {two_A[1][2]} = {B[1][2] - two_A[1][2]}")

#  Print the final result of B - 2A
print(f"\nFinal result of B - 2A: \n{result_B_minus_2A}")

First row of A: [ 2  1 -1]
  First element: 2 * 2 = 4
  Second element: 2 * 1 = 2
  Third element: 2 * -1 = -2
Second row of A: [ 1 -1  1]
  First element: 2 * 1 = 2
  Second element: 2 * -1 = -2
  Third element: 2 * 1 = 2

Performing subtraction: B - 2A
First row of B: [ 4 -2  1]
  First element: 4 - 4 = 0
  Second element: -2 - 2 = -4
  Third element: 1 - -2 = 3
Second row of B: [ 2 -4 -2]
  First element: 2 - 2 = 0
  Second element: -4 - -2 = -2
  Third element: -2 - 2 = -4

Final result of B - 2A: 
[[ 0 -4  3]
 [ 0 -2 -4]]


10.2.1 (c) 3C − 2E 

In this case, C has a shape of (2,2)(2 rows, 2 columns), and E has a shape of (2,1) 
(2 rows, 1 column). These matrices cannot be directly subtracted because their shapes don't align properly.
However, NumPy supports broadcasting. Broadcasting allows NumPy to perform operations 
on arrays of different shapes in certain circumstances. The answer has been shown in below python code

In [1405]:
# 10.2.1 (c) 3C − 2E

C = np.array([[1, 2], [2, 1]])
E = np.array([[1], [2]])


# Scalar multiplication by 3 (3C)
three_C = 3 * C
# Scalar multiplication by 2 (2E)
two_E = 2 * E

result = three_C - two_E
print("\nResult of 3C - 2E:")
print(result)


Result of 3C - 2E:
[[ 1  4]
 [ 2 -1]]


In [1406]:
#10.2.1 (d) 2D − 3C
D = np.array([[3, 4], [4, 3]])
C = np.array([[1, 2], [2, 1]])

# Scalar multiplication by 2 (2E)
two_D = 2 * D

#  Print the  result (2D)
print(f"\nMatrix  2D: \n{two_D}")

# Scalar multiplication by 3 (3C)
three_C = 3 * C

#  Print the  result (3C)
print(f"\nMatrix 3C: \n{three_C}")

#  the element-wise subtraction 2D - 3C
result = two_D - three_C
print("\nResult of 2D - 3C matrix:")
print(result)




Matrix  2D: 
[[6 8]
 [8 6]]

Matrix 3C: 
[[3 6]
 [6 3]]

Result of 2D - 3C matrix:
[[3 2]
 [2 3]]


In [1407]:
# 10.2.1  (e) D⊤ + 2D
D = np.array([[3, 4], [4, 3]])
#   the transpose of D (D^T)
D_transpose = D.T
print(" Transpose of D (D^T):")
print(D_transpose)

#   2D (scalar multiplication)
two_D = 2 * D
print("\n Scalar multiplication 2D:")
print(two_D)

#  Add D^T and 2D element-wise
result = D_transpose + two_D
print("\nResult of D^T + 2D:")
print(result)


 Transpose of D (D^T):
[[3 4]
 [4 3]]

 Scalar multiplication 2D:
[[6 8]
 [8 6]]

Result of D^T + 2D:
[[ 9 12]
 [12  9]]


In [1408]:
# 10.2.1  (f) 2C⊤ − 2D⊤
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

#  the transpose of C (C^T)
C_transpose = C.T
print("Transpose of C (C^T):")
print(C_transpose)

#   2C^T (scalar multiplication)
two_C_transpose = 2 * C_transpose
print("\nScalar multiplication 2C^T:")
print(two_C_transpose)

#   the transpose of D (D^T)
D_transpose = D.T
print("\nStep 3: Transpose of D (D^T):")
print(D_transpose)

# 2D^T (scalar multiplication)
two_D_transpose = 2 * D_transpose
print("\nScalar multiplication 2D^T:")
print(two_D_transpose)

#  element-wise subtraction 2C^T - 2D^T
result = two_C_transpose - two_D_transpose
# Final result
print("\nResult of 2C^T - 2D^T:")
print(result)




Transpose of C (C^T):
[[1 2]
 [2 1]]

Scalar multiplication 2C^T:
[[2 4]
 [4 2]]

Step 3: Transpose of D (D^T):
[[3 4]
 [4 3]]

Scalar multiplication 2D^T:
[[6 8]
 [8 6]]

Result of 2C^T - 2D^T:
[[-4 -4]
 [-4 -4]]


In [1409]:
# 10.2.1 (g) A⊤ − B
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

#  the transpose of A
A_transpose = A.T
print("A Transpose (A^T):")
print(A_transpose)

print("\nMatrix B:")
print(B)

# Attempt to perform A^T - B
try:
    result = A_transpose - B
    print("\nResult of A^T - B:")
    print(result)
except ValueError as e:
    print("\nError: Matrices A^T and B have different dimensions and cannot be subtracted.")
    print(f"Details: {e}")

A Transpose (A^T):
[[ 2  1]
 [ 1 -1]
 [-1  1]]

Matrix B:
[[ 4 -2  1]
 [ 2 -4 -2]]

Error: Matrices A^T and B have different dimensions and cannot be subtracted.
Details: operands could not be broadcast together with shapes (3,2) (2,3) 


In [1410]:
# 10.2.1 (h) AC
A = np.array([[2, 1, -1], [1, -1, 1]])
C = np.array([[1, 2], [2, 1]])

# t matrix multiplication
try:
    result = np.dot(A, C)  # or A @ C
    print("Result of AC:")
    print(result)
except ValueError as e:
    print("\nError: Matrices A and C have incompatible dimensions for multiplication.")
    print(f"Details: {e}")

# Print dimensions 
print("\nDimensions of A:", A.shape)
print("Dimensions of C:", C.shape)


Error: Matrices A and C have incompatible dimensions for multiplication.
Details: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

Dimensions of A: (2, 3)
Dimensions of C: (2, 2)


In [1411]:
# 10.2.1 (i) CD
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

print("After matrix multiplication, the result matrix is\n", C @ D)



After matrix multiplication, the result matrix is
 [[11 10]
 [10 11]]


In [1412]:
# 10.2.1 (j) CB
C = np.array([[1, 2], [2, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

result = np.dot(C, B)  #  equivalent to C @ B

print("Matrix C:")
print(C)

print("\nMatrix B:")
print(B)


# the  result
print("\nFinal result of CB:")
print(result)


Matrix C:
[[1 2]
 [2 1]]

Matrix B:
[[ 4 -2  1]
 [ 2 -4 -2]]

Final result of CB:
[[  8 -10  -3]
 [ 10  -8   0]]


In [1413]:
# 10.2.1 (k) CI
C = np.array([[1, 2], [2, 1]])
I = np.array([[1, 0], [0, 1]])

C @ I

array([[1, 2],
       [2, 1]])

In [1414]:
#10.2.1 (k) CI - Answer in another way
C = np.array([[1, 2], [2, 1]])
I = np.array([[1, 0], [0, 1]])

print("Matrix C:")
print(C)

print("Matrix I:")
print(I)

result = np.dot(C, I)  #  is equivalent to C @ I

# Print  multiplying C by I
print("\nResult of CI:")
print(result)

Matrix C:
[[1 2]
 [2 1]]
Matrix I:
[[1 0]
 [0 1]]

Result of CI:
[[1 2]
 [2 1]]


In [1415]:
# 10.2.1 (l) AB⊤
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

B_T = B.T  # Transpose of matrix B

# matrix multiplication: A * B^T
result = np.dot(A, B_T)  #  equivalent to A @ B.T

# Print the matrices and the result
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nTranspose of B (B^T):")
print(B_T)

print("\nResult of AB^T:")
print(result)

Matrix A:
[[ 2  1 -1]
 [ 1 -1  1]]

Matrix B:
[[ 4 -2  1]
 [ 2 -4 -2]]

Transpose of B (B^T):
[[ 4  2]
 [-2 -4]
 [ 1 -2]]

Result of AB^T:
[[5 2]
 [7 4]]


In [1416]:
# Uppgift 10.2.2. Definiera matrisen
A = np.array([[2, 3, 4], [5, 4, 1]])
print("Matrix A :\n", A)
#  transpose of A (A^T)
A_T = A.T
print("Transpose Matrix of A i.e AT :\n", A_T)
#  the matrix result
result_A_A_T = A @ A_T
print("\n result of A * A^T:")
print(result_A_A_T)


Matrix A :
 [[2 3 4]
 [5 4 1]]
Transpose Matrix of A i.e AT :
 [[2 5]
 [3 4]
 [4 1]]

 result of A * A^T:
[[29 26]
 [26 42]]


In [1417]:
# 10.2.3. Define the matrices. Verify that AB = AC but that B = C. 
# What we want to demonstrate with this example 
# is that we have defined a new mathematical object (matrices in this case) 
# and that the “usual rules” of arithmetic that 
# we learned from elementary school do not necessarily apply here.

#  matrices A, B, and C
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

# matrix multiplication AB
AB = np.dot(A, B)
print(" AB = A @ B")
print("AB matrix: \n", AB)

#  matrix multiplication AC
AC = np.dot(A, C)
print("\n AC = A @ C")
print("AC matrix: \n", AC)

#  Verify if AB == AC (element-wise comparison)
print("\n Verify if AB == AC:")
if np.array_equal(AB, AC):
    print("AB is equal to AC!")
else:
    print("AB is NOT equal to AC!")

#  Check if B != C (element-wise comparison)
print("\n Check if B != C:")
if np.array_equal(B, C):
    print("B is equal to C!")
else:
    print("B is NOT equal to C!")



 AB = A @ B
AB matrix: 
 [[ 4  7]
 [ 8 14]]

 AC = A @ C
AC matrix: 
 [[ 4  7]
 [ 8 14]]

 Verify if AB == AC:
AB is equal to AC!

 Check if B != C:
B is NOT equal to C!


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [1418]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [1419]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [1420]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [1421]:
v1 = np.arange(4)  # Create a NumPy array [0, 1, 2, 3]
print("Original v1:", v1)

#  Create a sliced view (v2) from v1
v2 = v1[-2:]  # Slice v1 from index -2 to the end, which results in [2, 3]
print("Sliced v2:", v2)

# to  check the base attribute to verify if v2 is a view of v1
print("\nBase of v1:", v1.base)  # None because v1 is the original array
print("Base of v2:", v2.base)    # v1, since v2 is a view of v1

#  Modify the last element of v2
v2[-1] = 123  # Change the last element of v2 to 123
print("\nModified v1:", v1)  # Should print [0 1 2 123]
print("Modified v2:", v2)    # Should print [2 123]

#  Analyze why v1 is modified when v2 is modified
print("\nExplanation:")
print("Since v2 is a view of v1, they share the same underlying data buffer.")
print("Thus, modifying the data in v2 also modifies v1.")

Original v1: [0 1 2 3]
Sliced v2: [2 3]

Base of v1: None
Base of v2: [0 1 2 3]

Modified v1: [  0   1   2 123]
Modified v2: [  2 123]

Explanation:
Since v2 is a view of v1, they share the same underlying data buffer.
Thus, modifying the data in v2 also modifies v1.
